--SQL Retail Sales Analysis Project--
Create Database SQL_Retail_Analysis;


--Create Table--
CREATE TABLE SALES_ANALYSIS
    {

}


--VIEW DATASET
 SELECT * FROM SALES_ANALYSIS;

 
----COUNT NUMBER OF ROWS--
 SELECT COUNT(*) FROM SALES_ANALYSIS;
 
---CHECK NULL VALUES IN EACH COLUMN---
SELECT TRANSACTIONS_ID FROM SALES_ANALYSIS WHERE TRANSACTIONS_ID IS NULL;
SELECT SALE_DATE FROM SALES_ANALYSIS WHERE SALE_DATE IS NULL;

----CHECK ALL THE NULL VALUES--
SELECT * FROM SALES_ANALYSIS WHERE 
TRANSACTIONS_ID IS NULL 
OR
SALE_DATE IS NULL
OR
SALE_TIME IS NULL
OR
CUSTOMER_ID IS NULL
OR
GENDER IS NULL
OR
AGE IS NULL
OR
CATEGORY IS NULL
OR
QUANTIY IS NULL
OR
PRICE_PER_UNIT IS NULL
OR 
COGS IS NULL
OR 
TOTAL_SALE IS NULL;

---DELETE MONEY RELATED NULL VALUES----
DELETE  FROM SALES_ANALYSIS
WHERE
TRANSACTIONS_ID IS NULL 
OR
SALE_DATE IS NULL
OR
SALE_TIME IS NULL
OR
CUSTOMER_ID IS NULL
OR
GENDER IS NULL
OR
CATEGORY IS NULL
OR
QUANTIY IS NULL
OR
PRICE_PER_UNIT IS NULL
OR 
COGS IS NULL
OR 
TOTAL_SALE IS NULL;

--REPLACE NULL AGE WITH 0 
UPDATE SALES_ANALYSIS
SET AGE = (SELECT  AVG(AGE) FROM SALES_ANALYSIS) 
WHERE AGE IS NULL;

--DATA EXPLORATION
--HOW MANY SALES WE HAVE
SELECT COUNT(TRANSACTIONS_ID) FROM SALES_ANALYSIS;

--HOW MANY  UNIQUE CUSTOMER WE HAVE
SELECT COUNT( DISTINCT CUSTOMER_ID) FROM SALES_ANALYSIS;

-- HOW MANY CATEGORIES WE HAVE 
SELECT COUNT( DISTINCT CATEGORY ) FROM SALES_ANALYSIS;
--DATA ANALYSIS OR BUSINESS KEY PROBLEMS

-- Q-1 WRITE A QUERY TO RETRIVE ALL THE COLUMNS OF SALES MADE ON 2022-11-05
SELECT * FROM SALES_ANALYSIS WHERE SALE_DATE = '2022-11-05';

---Q-2 WRITE A QUERY TO RETRIVE ALL THE COLUMNS WHERE CATEGORY IS CLOTHING AND QUANTITY SOLD IS MORE THEN 10 IN THE MONTH OF NOV 2022
SELECT CATEGORY, QUANTIY, SALE_DATE FROM SALES_ANALYSIS 
WHERE CATEGORY = 'CLOTHING' 
AND QUANTIY >= 4 
AND SALE_DATE BETWEEN '2022-11-01' AND '2022-11-30';

--Q-3 WRITE A QUERY TO CLACULATE TOTAL SALE FOR EACH CATEGORY
SELECT CATEGORY, SUM(TOTAL_SALE), COUNT(TOTAL_SALE) FROM SALES_ANALYSIS
GROUP BY CATEGORY;

--Q-4 WRITE THE AVERAGE AGE OF THE CUSTOMER WHO PURCHASE BEAUTY CATEGORY
SELECT CATEGORY, ROUND(AVG(AGE),2) AS AVERAGE_AGE
 FROM SALES_ANALYSIS
WHERE CATEGORY= 'Beauty'
GROUP BY CATEGORY;

--Q-5 WRITE SQL QUERY TO FIND ALL TRANSACTIONS WHERE TOTAL SALE IS GREATER THEN 1000
SELECT TRANSACTIONS_ID, TOTAL_SALE FROM SALES_ANALYSIS
WHERE TOTAL_SALE > 1000;

--Q-6 WRITE A SQL QUERY TO FIND TOTAL NUMBER OF TRANSACTION ID MADE BY EACH GENDER IN EACH CATEGORY
SELECT COUNT(TRANSACTIONS_ID), CATEGORY, GENDER
FROM SALES_ANALYSIS
GROUP BY CATEGORY, GENDER
ORDER BY CATEGORY DESC;

--Q-7 WRITE QUERY FOR AVERAGE SALE FOR EACH MONTH AND FIND BEST SELLING MONTH
SELECT 
EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
EXTRACT(MONTH FROM SALE_DATE) AS MONTH,
AVG(TOTAL_SALE) AS AVERAGE_SALE
FROM SALES_ANALYSIS
GROUP BY 1,2 
ORDER BY AVERAGE_SALE DESC;

--Q-8 WRITE QUERY TO GET THE TOTAL SALE FOR EACH CATEGORY
 SELECT CATEGORY, SUM(TOTAL_SALE) AS SALES_TOTAL
 FROM SALES_ANALYSIS
 GROUP BY CATEGORY
 ORDER BY SALES_TOTAL DESC;

--Q-9 WRITE QUERY TO FIND TOP 5 CUSTOMERS ON THE BASES OF SALES
SELECT DISTINCT CUSTOMER_ID, SUM(TOTAL_SALE) AS SALES
FROM SALES_ANALYSIS
GROUP BY DISTINCT CUSTOMER_ID
ORDER BY SALES DESC
LIMIT 5;

--Q-10 WRITE QUERY TO FIND NUMBER OF UNIQUE CUSTOMERS WHO BUY ORDERS FROM EACH CATEGORY
SELECT COUNT(DISTINCT CUSTOMER_ID), CATEGORY
FROM SALES_ANALYSIS
GROUP BY CATEGORY;

--Q-11 WRITE A SQL QUERY TO CREATE EACH SHIFT AND NUMBER OF ORDERS LIKE IN MORNING, AFTERNOON AND EVENING


WITH HOURLY_SALES AS

(
SELECT *,
    CASE
        WHEN EXTRACT( HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
	    WHEN EXTRACT( HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
	    ELSE 'EVENING'
	    END AS SHIFT
FROM SALES_ANALYSIS
)  
SELECT SHIFT,COUNT(*) AS TOTAL_ORDERS FROM HOURLY_SALES

GROUP BY SHIFT
ORDER BY TOTAL_ORDERS DESC;
 --END OF THE PROJECT--













 